### ISSUE TITLE
Write good callback abstraction

### ISSUE THREAD

**Issue by MBkkt** [YACLib/YACLib#19]
`ITask` <=> Intrusive node + vtable + `virtual void Call() = 0`

`detail::Task(functor<void()>)` -> Functor member + public inheritance `ITask`, `void Call()` call `functor<void()>`

detail::CallbackTask(functor<void(Args...)>) ->  Functor member + raw memory for Args +  public inheritance `ITask`, `void Call()` call `functor<void(Args...)>`(Args...),  method some like SetArgs(Args...)

CreateCallback <=> detail::CallbackTask(functor<void(Args...)>)
when we should execute callback and know its args we:
callback->SetArgs(args...);
tp->Execute(callback)
or if inline callback call
callback->Call(args....)

**Comment by kononovk** [comment]
Will be done in #26
