### ISSUE TITLE
Add CI

### ISSUE THREAD

**Issue by MBkkt** [YACLib/YACLib#6]
* Use GitHub actions
* Build library, tests, benchmarks for all checked configurations
  * Linux + Clang
  * Linux + GCC
  * Windows + MSVC
  * OS X + AppleClang
  * Windows + other compilers (if possible)
  * Android + GCC (if possible)
  * Android + Clang (if possible)
  * IOS + AppleClang (if possible)
* Check with clang-format
* Check with clang-tidy #8
* Run tests with sanitizers #7

**Comment by kononovk** [comment]
- [ ]
